export default {
    after: (field, [target]) => `O campo acima deve estar depois do campo ${target}.`,
    alpha_dash: (field) => `O campo acima deve conter letras, números e traços.`,
    alpha_num: (field) => `O campo acima deve conter somente letras e números.`,
    alpha_spaces: (field) => `The ${field} só pode conter caracteres alfabéticos e espaços.`,
    alpha: (field) => `O campo acima deve conter somente letras.`,
    before: (field, [target]) => `O campo acima deve estar antes do campo ${target}.`,
    between: (field, [min, max]) => `O campo acima deve estar entre ${min} e ${max}.`,
    confirmed: (field, [confirmedField]) => `O campo acima e ${confirmedField} devem ser iguais.`,
    credit_card: (field) => `O campo acima é inválido.`,
    date_between: (field, [min, max]) => `O campo acima deve estar entre ${min} e ${max}.`,
    date_format: (field, [format]) => `O campo acima deve estar no formato ${format}.`,
    decimal: (field, [decimals] = ['*']) => `O campo acima deve ser numérico e deve conter ${decimals === '*' ? '' : decimals} casas decimais.`,
    digits: (field, [length]) => `O campo acima deve ser numérico e ter ${length} dígitos.`,
    dimensions: (field, [width, height]) => `O campo acima deve ter ${width} pixels de largura por ${height} pixels de altura.`,
    email: (field) => `O campo acima deve ser um email válido.`,
    ext: (field) => `O campo acima deve ser um arquivo válido.`,
    image: (field) => `O campo acima deve ser uma imagem.`,
    in: (field) => `O campo acima deve ter um valor válido.`,
    ip: (field) => `O campo acima deve ser um endereço IP válido.`,
    max: (field, [length]) => `O campo acima não deve ter mais que ${length} caracteres.`,
    max_value: (field, [max]) => `O campo acima precisa ser ${max} ou menor.`,
    mimes: (field) => `O campo acima deve ser um tipo de arquivo válido.`,
    min: (field, [length]) => `O campo acima deve conter pelo menos ${length} caracteres.`,
    min_value: (field, [min]) => `O campo acima precisa ser ${min} ou maior.`,
    not_in: (field) => `O campo acima deve ser um valor válido.`,
    numeric: (field) => `O campo acima deve conter apenas números`,
    regex: (field) => `O campo acima possui um formato inválido.`,
    required: (field) => `O campo acima é obrigatório.`,
    size: (field, [size]) => `O campo acima deve ser menor que ${size} KB.`,
    url: (field) => `O campo acima não é uma URL válida.`
};